
spring.application.name=assistant
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=
gemini.api.key=AIzaSyAQf5XSXpAc-AoUbXUEgkApfuJUzB8EEkQ
server.port=8080

# Gemini AI Configuration
gemini.api.key=AIzaSyAQf5XSXpAc-AoUbXUEgkApfuJUzB8EEkQ
gemini.api.url=https://api.gemini.ai/v1

# Logging Configuration
logging.level.root=INFO
logging.level.com.research.assistant=DEBUG